services:
  - type: web
    name: update-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn updaterapi:app --bind 0.0.0.0:$PORT
    autoDeploy: true
